### ISSUE TITLE
control_url seems to be undefined

### ISSUE THREAD

**Issue by udl** [unboxed/newrelic_puma_plugin#3]
Hi,
I'm seeing the following stacktrace:

```
[2014-12-05 10:37:50 UTC] INFO: Using Ruby SDK version: 1.3.1
[2014-12-05 10:37:50 UTC] INFO: Agent Puma Agent is at version 0.0.2
[2014-12-05 10:37:50 UTC] DEBUG: Start collecting agent data for poll cycle
[2014-12-05 10:37:50 UTC] ERROR: Error occurred in poll cycle: undefined method `gsub' for nil:NilClass
[2014-12-05 10:37:50 UTC] DEBUG: Stacktrace:
./newrelic_puma_agent:22:in `control_url'
./newrelic_puma_agent:30:in `control_url_and_auth_token'
./newrelic_puma_agent:47:in `poll_cycle'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/agent.rb:139:in `run'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:143:in `block in run_agent_data_collection'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `each'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `run_agent_data_collection'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:127:in `loop_forever'
/home/apps/.rvm/gems/ruby-2.1.2/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:15:in `setup_and_run'
```

Any idea, what I'm doing wrong?
control_url seems to be missing from the config ... but which config is it? and what should the control_url look like?

**Comment by udl** [comment]
using newrelic_rpm now ... thx
