### ISSUE TITLE
ERROR: Error occurred in poll cycle: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by thehappycoder** [unboxed/newrelic_puma_plugin#5]
[2015-10-31 14:30:35 UTC] INFO: Using Ruby SDK version: 1.3.1
[2015-10-31 14:30:35 UTC] INFO: Agent Puma Agent is at version 0.0.2
[2015-10-31 14:30:35 UTC] DEBUG: Start collecting agent data for poll cycle
[2015-10-31 14:30:35 UTC] ERROR: Error occurred in poll cycle: undefined method `gsub' for nil:NilClass
[2015-10-31 14:30:35 UTC] DEBUG: Stacktrace:
./newrelic_puma_agent:21:in`control_url'
./newrelic_puma_agent:29:in `control_url_and_auth_token'
./newrelic_puma_agent:46:in`poll_cycle'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/agent.rb:139:in `run'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:143:in`block in run_agent_data_collection'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `each'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in`run_agent_data_collection'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:127:in `loop_forever'
/usr/local/rvm/gems/ruby-2.2.3/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:15:in`setup_and_run'
./newrelic_puma_agent:71:in `<module:PumaAgent>'
./newrelic_puma_agent:36:in`<main>'
[2015-10-31 14:30:35 UTC] DEBUG: Finished collecting agent data for poll cycle
[2015-10-31 14:30:35 UTC] DEBUG: Component with name "cleancode.co
" and guid "com.ubxd.newrelic_puma" had no metrics
[2015-10-31 14:30:35 UTC] DEBUG: JSON payload: {"agent":{"version":"0.0.2"},"components":[]}
[2015-10-31 14:30:35 UTC] INFO: Gathered 0 statistics from 0 components

ruby-2.2.3

**Comment by thehappycoder** [comment]
## State file:

pid: 2038
config: !ruby/object:Puma::Configuration
  options:
    :min_threads: 2
    :max_threads: 10
    :quiet: false
    :debug: false
    :binds:
    - unix:///tmp/satsanga.sock
    :workers: 1
    :daemon: true
    :worker_directory: "/home/satsanga/app/satsanga"
    :config_file: config/puma.rb
    :mode: :http
    :worker_timeout: 60
    :worker_shutdown_timeout: 30
    :environment: production
    :pidfile: "/home/satsanga/app/satsanga/tmp/pids/satsanga.pid"
    :state: "/home/satsanga/app/satsanga/tmp/pids/satsanga.state"
    :control_auth_token: 5582291ce0679c99f6789853c2ce6a73
    :tag: satsanga
